name: Backup to S3

on:
  push:
    branches:
      - '**'

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Optional: GitHub Repository auschecken, falls du lokal arbeiten willst
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Holt alle Branches und Tags

      # AWS Credentials konfigurieren
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::135278927571:role/GitHub_Backup_OIDC_Role
          aws-region: eu-central-1

      # Git Mirror erzeugen
      - name: Mirror repository
        run: |
          mkdir -p backup
          git clone --mirror .git backup/repo.git

      # Mirror zu S3 synchronisieren
      - name: Sync to S3
        run: |
          aws s3 sync backup/repo.git s3://ifena-github-backup/${{ github.repository }}.git --delete
